#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug  4 18:42:15 2020

@author: nsbhatta
"""


def is_leap(year):
    leap = False
    
    if year % 4 == 0:
        if year % 100 != 0:
            leap = True
            return leap
        else:
            if year % 400 == 0:
                leap = True
                return leap
                
    
    return leap

year = int(input())
print(is_leap(year))